root: true
env:
  browser: true
  node: true
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
extends:
  - '@nuxtjs/eslint-config-typescript'
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  comma-dangle:
    - error
    - never
  func-names:
    - error
    - as-needed
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  no-empty:
    - error
    - allowEmptyCatch: true
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  import/prefer-default-export: off
  import/no-useless-path-segments: off
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/semi': error
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-inferrable-types': error
  'vue/singleline-html-element-content-newline': off
  'no-undef': off
  'vue/multi-word-component-names': off
